### ISSUE TITLE
Any update for supporting latest android?

### ISSUE THREAD

**Issue by MF-Debug** [pragma-/networklog#23]
Hi, is there any plan to revamp the app to support latest android versions?

**Comment by pragma-** [comment]
Is there something specific you had in mind?

**Comment by MF-Debug** [comment]
nothing in particular, just asking as it gives a warning while installing saying this app is not built for latest android. I suppose this is because it lacks the support for latest sdk version? Also, the interface looks bad on my android 11 rom.

**Comment by pragma-** [comment]
Would you mind sharing a screenshot and description of what looks bad?
